import "../TSX-Folder/CSS-Folder/Globals.css"
import type {} from "react";
type RootLayoutProps = {
  children: React.ReactNode;
}

export const metadata = {
  title: "SURFACE OFFICIAL WEBSITE",
  description: "Generated by create next app",
};

const RootLayout: React.FC<RootLayoutProps> = (props) => {
  return (
    <html lang="ja">
      <body className="">{props.children}</body>
    </html>
  );
};